## STATIC CONFIGURATION
log:
  level: INFO

api:
  insecure: true
  dashboard: true

## TRAEFIK PILOT MONITOR API TOKEN (IGNORE DAT)
#pilot:
#    token: "8b9b0234-36f6-4326-9caf-cdfgdijfgi59"

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  ws:  
    address: ":81"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  lets-encr:
    acme:
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: tomas@saiyans.com.ve
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
